import { mount, flushPromises } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import App from './App.vue'
import { api } from './api'
vi.mock('./api', () => ({ api: { login: vi.fn(), logout: vi.fn(), request: vi.fn() } }))
const people = [{ id: 'alice', name: 'Alice' }, { id: 'bob', name: 'Bob' }, { id: 'carol', name: 'Carol' }]
const start = { id: 'start', type: 'start', name: 'Submit request', assigneeId: null }
const end = { id: 'end', type: 'end', name: 'Completed', assigneeId: null }
const manager = { id: 'manager', type: 'approval', name: 'Manager review', assigneeId: 'bob' }
const finance = { id: 'finance', type: 'approval', name: 'Final review', assigneeId: 'carol' }
const blueprint = { schemaVersion: 2, id: 'leave-approval', version: 1, name: 'Leave approval', nodes: [start, manager, end] }
const sequence = { ...blueprint, nodes: [start, manager, finance, end] }
const clone = value => JSON.parse(JSON.stringify(value))
function request(definition = blueprint, overrides = {}) {
  return { id: 'r1', title: 'Annual leave', reason: 'Family trip', days: 2, applicantId: 'alice', approverId: 'bob', currentStepId: 'manager', status: 'PENDING', createdAt: '2026-10-02T12:00:00Z', updatedAt: '2026-10-02T12:00:00Z', decision: null, comment: null, processId: 'leave-approval', processVersion: definition.version, definition: clone(definition), history: [{ actorId: overrides.applicantId || 'alice', action: 'SUBMIT', stepId: null, comment: '', at: '2026-10-02T12:00:00Z' }], ...overrides }
}
function setup(identity = 'alice', items = [], definition = blueprint) {
  const server = { identity, items: clone(items), definition: clone(definition) }
  api.request.mockImplementation(async path => clone({ '/me': people.find(p => p.id === server.identity), '/people': people, '/process': server.definition, '/requests': server.items }[path]))
  return { wrapper: mount(App), server }
}
async function login(wrapper) {
  await wrapper.find('input[type=password]').setValue('demo-password')
  await wrapper.find('.login-form').trigger('submit')
  await flushPromises()
}
async function designer(wrapper) { await wrapper.find('[data-testid="process-tab"]').trigger('click'); await wrapper.find('[data-testid="workspace-language"]').setValue('en') }
async function selectStep(wrapper, index) { await wrapper.findAll('[data-testid="select-step"]')[index - 1].trigger('click') }
async function requestForm(wrapper) {
  await wrapper.find('.new-request input[maxlength="120"]').setValue('Annual leave')
  await wrapper.find('.new-request textarea').setValue('Family trip')
  await wrapper.find('.new-request input[type=number]').setValue('2')
}
const button = (wrapper, id) => wrapper.find(`[data-testid="${id}"]`)
const posts = () => api.request.mock.calls.filter(([, options]) => options?.method === 'POST')
const payload = () => JSON.parse(posts().at(-1)[1].body)
const deferred = () => { let resolve, reject; const promise = new Promise((yes, no) => { resolve = yes; reject = no }); return { promise, resolve, reject } }
const decideResult = (item, stepId, actorId, status, currentStepId, approverId, action = 'APPROVE') => ({ ...item, status, currentStepId, approverId, updatedAt: '2026-10-02T13:00:00Z', decision: action, comment: 'Reviewed', history: [...item.history, { actorId, action, stepId, comment: 'Reviewed', at: '2026-10-02T13:00:00Z' }] })
beforeEach(() => vi.resetAllMocks())

describe('authentication and session isolation', () => {
  it('clears the password and supports identity name from the API', async () => {
    const { wrapper } = setup(); await login(wrapper)
    expect(api.login).toHaveBeenCalledWith('alice', 'demo-password')
    expect(wrapper.find('.sidebar-bottom').text()).toContain('Alice')
    await wrapper.find('[aria-label="Sign out"]').trigger('click')
    expect(wrapper.find('input[type=password]').element.value).toBe('')
  })
  it('shows login errors without entering the workspace or keeping credentials', async () => {
    const { wrapper } = setup(); api.request.mockRejectedValue(new Error('Unauthorized')); await login(wrapper)
    expect(wrapper.find('[role=alert]').text()).toContain('Check the demo account and its server-configured password')
    expect(wrapper.find('.workspace').exists()).toBe(false)
    expect(api.logout).toHaveBeenCalled()
    expect(wrapper.find('input[type=password]').element.value).toBe('')
  })
  it('suppresses repeated login attempts', async () => {
    const { wrapper } = setup(); const pending = deferred()
    api.request.mockImplementationOnce(() => pending.promise)
    await wrapper.find('input[type=password]').setValue('demo-password')
    await wrapper.find('.login-form').trigger('submit'); await wrapper.find('.login-form').trigger('submit')
    expect(api.login).toHaveBeenCalledTimes(1)
    pending.resolve(people[0]); await flushPromises()
    expect(wrapper.find('.workspace').exists()).toBe(true)
  })
})

describe('sequential process designer', () => {
  it('has a fixed start and end and an editable named assigned approval', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    expect(wrapper.findAll('.flow-node').map(node => node.attributes('data-step-id'))).toEqual(['start', 'manager', 'end'])
    expect(wrapper.findAll('.flow-node.start input, .flow-node.end input')).toHaveLength(0)
    expect(wrapper.find('[aria-label="Step 1 name"]').element.value).toBe('Manager review')
    expect(wrapper.find('[aria-label="Step 1 approver"]').element.value).toBe('bob')
    expect(wrapper.find('[aria-label="Move step 1 up"]').attributes('disabled')).toBeDefined()
    expect(wrapper.find('[aria-label="Move step 1 down"]').attributes('disabled')).toBeDefined()
    expect(wrapper.find('[aria-label="Remove step 1"]').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
  })
  it('adds, names, assigns, reorders, and removes uniquely identified steps', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'add-step').trigger('click')
    await wrapper.find('[aria-label="Step 2 name"]').setValue('Director review')
    await wrapper.find('[aria-label="Step 2 approver"]').setValue('carol')
    const newId = wrapper.findAll('.flow-node.approval')[1].attributes('data-step-id')
    expect(newId).not.toBe('manager')
    await wrapper.find('[aria-label="Move step 2 up"]').trigger('click')
    expect(wrapper.findAll('.flow-node').map(node => node.attributes('data-step-id'))).toEqual(['start', newId, 'manager', 'end'])
    expect(wrapper.find('[aria-label="Step 1 name"]').element.value).toBe('Director review')
    await wrapper.find('[aria-label="Move step 1 down"]').trigger('click')
    expect(wrapper.findAll('.flow-node.approval').map(node => node.attributes('data-step-id'))).toEqual(['manager', newId])
    await selectStep(wrapper, 1)
    await wrapper.find('[aria-label="Remove step 1"]').trigger('click')
    expect(wrapper.findAll('.flow-node.approval')).toHaveLength(1)
    expect(wrapper.find('[aria-label="Step 1 name"]').element.value).toBe('Director review')
    expect(wrapper.find('[aria-label="Remove step 1"]').attributes('disabled')).toBeDefined()
  })
  it('allows at most eight steps and distinct steps assigned to the same person', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    for (let i = 0; i < 9; i++) await button(wrapper, 'add-step').trigger('click')
    const steps = wrapper.findAll('.flow-node.approval')
    expect(steps).toHaveLength(8)
    expect(new Set(steps.map(node => node.attributes('data-step-id'))).size).toBe(8)
    expect(steps.every(node => node.find('.review-people').text().includes('Bob'))).toBe(true)
    expect(button(wrapper, 'add-step').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'publish').attributes('disabled')).toBeUndefined()
  })
  it('resets the entire local draft without a server mutation', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue('Time off')
    await button(wrapper, 'add-step').trigger('click')
    await selectStep(wrapper, 1)
    await wrapper.find('[aria-label="Step 1 name"]').setValue('Changed')
    await button(wrapper, 'reset-draft').trigger('click')
    expect(button(wrapper, 'process-name').element.value).toBe('Leave approval')
    expect(wrapper.findAll('.flow-node.approval')).toHaveLength(1)
    expect(wrapper.find('[aria-label="Step 1 name"]').element.value).toBe('Manager review')
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
    expect(posts()).toHaveLength(0)
  })
  it('validates blank names before publishing', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue(' ')
    await wrapper.find('[aria-label="Step 1 name"]').setValue(' ')
    expect(wrapper.find('.validation-list').text()).toContain('Give the process a name')
    expect(wrapper.find('.validation-list').text()).toContain('Give approval step 1 a name')
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
    await button(wrapper, 'publish').trigger('click'); expect(posts()).toHaveLength(0)
  })
  it('publishes a complete definition with the pinned base version and trims names', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue(' Time off ')
    await wrapper.find('[aria-label="Step 1 name"]').setValue(' Manager sign-off ')
    await button(wrapper, 'add-step').trigger('click')
    await wrapper.find('[aria-label="Step 2 approver"]').setValue('carol')
    const expected = { ...clone(blueprint), name: 'Time off', nodes: [start, { ...manager, name: 'Manager sign-off' }, { id: 'approval-1', type: 'approval', name: 'Approval 2', assigneeId: 'carol' }, end] }
    api.request.mockResolvedValueOnce({ ...expected, version: 2 })
    await button(wrapper, 'publish').trigger('click'); await flushPromises()
    expect(posts()).toEqual([['/process', { method: 'POST', body: JSON.stringify({ expectedVersion: 1, definition: expected }) }]])
    expect(wrapper.text()).toContain('Template v2 published')
    expect(wrapper.text()).toContain('existing request snapshots are unchanged')
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
    expect(wrapper.text()).toContain('Draft based on v2')
  })
  it('suppresses repeated publishing and disables edits until completion', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue('Time off'); const pending = deferred()
    api.request.mockImplementationOnce(() => pending.promise)
    await button(wrapper, 'publish').trigger('click'); await button(wrapper, 'publish').trigger('click')
    expect(posts()).toHaveLength(1)
    expect(button(wrapper, 'add-step').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'reset-draft').attributes('disabled')).toBeDefined()
    expect(button(wrapper, 'process-name').attributes('disabled')).toBeDefined()
    pending.resolve({ ...blueprint, name: 'Time off', version: 2 }); await flushPromises()
    expect(button(wrapper, 'add-step').attributes('disabled')).toBeUndefined()
  })
  it('keeps a rejected draft and enables editing after server failure', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue('Time off')
    api.request.mockRejectedValueOnce(new Error('Service unavailable'))
    await button(wrapper, 'publish').trigger('click'); await flushPromises()
    expect(wrapper.find('[role=alert]').text()).toContain('Your draft is preserved')
    expect(button(wrapper, 'process-name').element.value).toBe('Time off')
    expect(button(wrapper, 'publish').attributes('disabled')).toBeUndefined()
    expect(wrapper.text()).toContain('Draft based on v1')
  })
  it('preserves stale edits on a 409 and guides refresh/reset recovery', async () => {
    const { wrapper, server } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue('My draft')
    api.request.mockRejectedValueOnce(Object.assign(new Error('Stale process version'), { status: 409 }))
    await button(wrapper, 'publish').trigger('click'); await flushPromises()
    expect(wrapper.find('[role=alert]').text()).toContain('Refresh to load the latest template, then reset')
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
    server.definition = { ...clone(sequence), version: 2, name: 'Updated elsewhere' }
    await button(wrapper, 'refresh').trigger('click'); await flushPromises()
    expect(button(wrapper, 'process-name').element.value).toBe('My draft')
    expect(wrapper.text()).toContain('Published v2'); expect(wrapper.text()).toContain('Draft based on v1')
    expect(button(wrapper, 'stale-draft').exists()).toBe(true)
    await button(wrapper, 'reset-draft').trigger('click')
    expect(button(wrapper, 'process-name').element.value).toBe('Updated elsewhere')
    expect(wrapper.findAll('.flow-node.approval')).toHaveLength(2)
    expect(wrapper.text()).toContain('Draft based on v2'); expect(button(wrapper, 'stale-draft').exists()).toBe(false)
    expect(posts()).toHaveLength(1)
  })
  it('refreshes both requests and the template while preserving a dirty draft', async () => {
    const { wrapper, server } = setup(); await login(wrapper); await designer(wrapper)
    await wrapper.find('[aria-label="Step 1 name"]').setValue('Local manager')
    server.definition = { ...clone(sequence), version: 2 }
    await button(wrapper, 'refresh').trigger('click'); await flushPromises()
    expect(wrapper.find('[aria-label="Step 1 name"]').element.value).toBe('Local manager')
    expect(wrapper.findAll('.flow-node.approval')).toHaveLength(1)
    expect(api.request).toHaveBeenCalledWith('/requests'); expect(api.request).toHaveBeenCalledWith('/process')
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
    expect(wrapper.find('[role=status]').text()).toContain('local draft is preserved')
  })
  it('updates a clean draft when refresh finds a newer published template', async () => {
    const { wrapper, server } = setup(); await login(wrapper); await designer(wrapper)
    server.definition = { ...clone(sequence), version: 2 }
    await button(wrapper, 'refresh').trigger('click'); await flushPromises()
    expect(wrapper.findAll('.flow-node.approval')).toHaveLength(2)
    expect(wrapper.text()).toContain('Draft based on v2'); expect(button(wrapper, 'stale-draft').exists()).toBe(false)
  })
  it('preserves a dirty draft when navigating away and back', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue('Unsaved sequence')
    await wrapper.find('nav button').trigger('click'); await designer(wrapper)
    expect(button(wrapper, 'process-name').element.value).toBe('Unsaved sequence')
  })
  it.each(['bob', 'carol'])('lets %s view the process without editor or publish controls', async identity => {
    const { wrapper } = setup(identity, [], sequence); await login(wrapper); await designer(wrapper)
    expect(wrapper.text()).toContain('Read-only template'); expect(wrapper.text()).toContain('Only Alice')
    expect(wrapper.find('.step-inspector input, .step-inspector select').exists()).toBe(false)
    expect(button(wrapper, 'add-step').exists()).toBe(false)
    expect(button(wrapper, 'reset-draft').exists()).toBe(false)
    expect(button(wrapper, 'publish').exists()).toBe(false)
    expect(wrapper.findAll('.review-people').map(node => node.text())).toEqual(['BBob', 'CCarol'])
  })
  it('ignores a publish response after sign out and erases the draft', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue('Private draft'); const pending = deferred()
    api.request.mockImplementationOnce(() => pending.promise)
    await button(wrapper, 'publish').trigger('click'); await wrapper.find('[aria-label="Sign out"]').trigger('click')
    pending.resolve({ ...blueprint, version: 2 }); await flushPromises()
    expect(wrapper.find('.workspace').exists()).toBe(false); expect(wrapper.text()).not.toContain('Private draft')
    await login(wrapper); await designer(wrapper)
    expect(button(wrapper, 'process-name').element.value).toBe('Leave approval')
  })
})

describe('request submission and snapshots', () => {
  it.each([
    ['partial object with a valid id', () => ({ id: 'r1' })],
    ['unknown status', () => request(blueprint, { status: 'UNKNOWN' })],
    ['null history event', () => request(blueprint, { history: [null] })],
    ['malformed definition', () => request(blueprint, { definition: { nodes: [null] } })],
    ['wrong applicant', () => request(blueprint, { applicantId: 'carol' })],
    ['wrong immutable intent', () => request(blueprint, { reason: 'Different' })],
  ])('preserves input and retry key for %s before accepting a confirmed response', async (_, response) => {
    const { wrapper } = setup(); await login(wrapper); await requestForm(wrapper)
    api.request.mockResolvedValueOnce(response())
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    const first = posts()[0][1]
    expect(button(wrapper, 'request-title').element.value).toBe('Annual leave')
    expect(wrapper.findAll('.request-item')).toHaveLength(0)
    api.request.mockResolvedValueOnce(request())
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(posts()[1][1]).toEqual(first)
    expect(wrapper.findAll('.request-item')).toHaveLength(1)
  })
  it('starts a new intent after explicit refresh following a definitive stale-version rejection', async () => {
    const { wrapper, server } = setup(); await login(wrapper); await requestForm(wrapper)
    api.request.mockRejectedValueOnce(Object.assign(new Error('The published process changed; reload before submitting'), { status: 409 }))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    const key = posts()[0][1].headers['Idempotency-Key']
    server.definition = { ...clone(blueprint), version: 2 }
    await button(wrapper, 'refresh').trigger('click'); await flushPromises()
    expect(button(wrapper, 'request-title').element.value).toBe('Annual leave')
    api.request.mockResolvedValueOnce(request(server.definition))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(payload().processVersion).toBe(2)
    expect(posts()[1][1].headers['Idempotency-Key']).not.toBe(key)
  })
  it('does not discard an attempt on generic or changed-intent conflict', async () => {
    const { wrapper, server } = setup(); await login(wrapper); await requestForm(wrapper)
    api.request.mockRejectedValueOnce(Object.assign(new Error('Idempotency-Key was already used for a different submission'), { status: 409 }))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    const first = posts()[0][1]
    server.definition = { ...clone(blueprint), version: 2 }
    await button(wrapper, 'refresh').trigger('click'); await flushPromises()
    api.request.mockResolvedValueOnce(request())
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(posts()[1][1]).toEqual(first)
  })
  it('retains the key and original version across uncertain failure, refresh and replay', async () => {
    const { wrapper, server } = setup('carol'); await login(wrapper); await requestForm(wrapper)
    const pending = deferred(); api.request.mockImplementationOnce(() => pending.promise)
    await wrapper.find('.new-request').trigger('submit'); await wrapper.find('.new-request').trigger('submit')
    expect(posts()).toHaveLength(1)
    const first = posts()[0][1]
    expect(first.headers['Idempotency-Key']).toMatch(/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/)
    pending.reject(new TypeError('Connection lost after commit')); await flushPromises()
    const accepted = request(blueprint, { applicantId: 'carol' })
    server.items = [accepted]
    // A new publication may even assign this applicant: retry uses the old snapshot.
    server.definition = { ...clone(blueprint), version: 2, nodes: [start, { ...manager, assigneeId: 'carol' }, end] }
    await button(wrapper, 'refresh').trigger('click'); await flushPromises()
    expect(button(wrapper, 'submission-template').text()).toContain('Leave approval · v1')
    expect(button(wrapper, 'submit-request').attributes('disabled')).toBeUndefined()
    api.request.mockResolvedValueOnce(accepted)
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(posts()[1][1]).toEqual(first)
    expect(wrapper.findAll('.request-item')).toHaveLength(1)
    expect(button(wrapper, 'request-title').element.value).toBe('')
    expect(button(wrapper, 'submission-template').text()).toContain('Leave approval · v2')
  })
  it.each(['network', 'server', 'malformed-success'])('keeps the key after %s and rotates it only for edited or completed intent', async failure => {
    const { wrapper } = setup(); await login(wrapper); await requestForm(wrapper)
    if (failure === 'malformed-success') api.request.mockResolvedValueOnce(null)
    else api.request.mockRejectedValueOnce(Object.assign(new Error('Unconfirmed write'), failure === 'server' ? { status: 503 } : {}))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    const first = posts()[0][1]
    api.request.mockRejectedValueOnce(new Error('Still offline'))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(posts()[1][1]).toEqual(first)
    await button(wrapper, 'request-reason').setValue('Changed reason')
    api.request.mockResolvedValueOnce(request(blueprint, { reason: 'Changed reason' }))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    const editedKey = posts()[2][1].headers['Idempotency-Key']
    expect(editedKey).not.toBe(first.headers['Idempotency-Key'])
    expect(payload().reason).toBe('Changed reason')
    await requestForm(wrapper)
    api.request.mockResolvedValueOnce(request(blueprint, { id: 'r2' }))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(posts()[3][1].headers['Idempotency-Key']).not.toBe(editedKey)
  })
  it('does not reuse an unresolved submission key after logout or accept its late response', async () => {
    const { wrapper } = setup(); await login(wrapper); await requestForm(wrapper)
    const pending = deferred(); api.request.mockImplementationOnce(() => pending.promise)
    await wrapper.find('.new-request').trigger('submit')
    const firstKey = posts()[0][1].headers['Idempotency-Key']
    await button(wrapper, 'sign-out').trigger('click')
    pending.resolve(request()); await flushPromises()
    expect(wrapper.find('.workspace').exists()).toBe(false)
    await login(wrapper); await requestForm(wrapper)
    api.request.mockResolvedValueOnce(request(blueprint, { id: 'r2' }))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(posts()[1][1].headers['Idempotency-Key']).not.toBe(firstKey)
  })
  it('submits using the published version without a chosen approver and shows the snapshot', async () => {
    const { wrapper } = setup(); await login(wrapper); await requestForm(wrapper)
    expect(wrapper.find('.new-request select').exists()).toBe(false)
    expect(button(wrapper, 'submission-template').text()).toContain('Manager review (Bob)')
    api.request.mockResolvedValueOnce(request())
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(payload()).toEqual({ title: 'Annual leave', reason: 'Family trip', days: 2, processVersion: 1 })
    expect(wrapper.find('.detail').text()).toContain('Awaiting review')
    expect(wrapper.text()).toContain('Request submitted. Bob')
    expect(button(wrapper, 'instance-snapshot').text()).toContain('Read-only snapshot from submission')
  })
  it('uses the published template instead of an unpublished local draft', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'add-step').trigger('click'); await wrapper.find('nav button').trigger('click')
    expect(button(wrapper, 'submission-template').text()).toContain('Your unpublished draft is not used')
    expect(button(wrapper, 'submission-template').text()).not.toContain('Approval 2')
    await requestForm(wrapper); api.request.mockResolvedValueOnce(request())
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(payload().processVersion).toBe(1)
  })
  it('keeps an existing request snapshot unchanged after publishing a different sequence', async () => {
    const original = request(); const { wrapper } = setup('alice', [original]); await login(wrapper); await designer(wrapper)
    await wrapper.find('[aria-label="Step 1 name"]').setValue('New team review')
    await button(wrapper, 'add-step').trigger('click')
    api.request.mockResolvedValueOnce({ ...clone(sequence), version: 2, name: 'New process' })
    await button(wrapper, 'publish').trigger('click'); await flushPromises()
    await wrapper.find('nav button').trigger('click'); await wrapper.find('.request-item').trigger('click')
    expect(button(wrapper, 'submission-template').text()).toContain('New process · v2')
    const snapshot = button(wrapper, 'instance-snapshot')
    expect(snapshot.text()).toContain('Leave approval · v1')
    expect(snapshot.text()).toContain('Manager review'); expect(snapshot.text()).not.toContain('Final review')
    expect(snapshot.findAll('li')).toHaveLength(3)
    expect(snapshot.find('input, select, button').exists()).toBe(false)
  })
  it('prevents submission if any published approval step is self-assigned', async () => {
    const { wrapper } = setup('carol', [], sequence); await login(wrapper); await requestForm(wrapper)
    expect(wrapper.find('.new-request').text()).toContain('approval assigned to you')
    expect(wrapper.find('.new-request button').attributes('disabled')).toBeDefined()
    await wrapper.find('.new-request').trigger('submit'); expect(posts()).toHaveLength(0)
    expect(wrapper.find('[role=alert]').text()).toContain('assigns an approval step to you')
  })
  it('lets an approver submit a template that never assigns them', async () => {
    const { wrapper } = setup('carol'); await login(wrapper); await requestForm(wrapper)
    expect(wrapper.find('.new-request button').attributes('disabled')).toBeUndefined()
    api.request.mockResolvedValueOnce(request(blueprint, { applicantId: 'carol' }))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises(); expect(posts()).toHaveLength(1)
  })
  it('validates required request fields and integer days without posting', async () => {
    const { wrapper } = setup(); await login(wrapper)
    await wrapper.find('.new-request').trigger('submit'); expect(posts()).toHaveLength(0)
    await requestForm(wrapper); await wrapper.find('.new-request input[type=number]').setValue('1.5')
    await wrapper.find('.new-request').trigger('submit'); expect(posts()).toHaveLength(0)
    expect(wrapper.find('[role=alert]').text()).toContain('whole number')
  })
  it('suppresses repeated submissions while a request is in flight', async () => {
    const { wrapper } = setup(); await login(wrapper); await requestForm(wrapper); const pending = deferred()
    api.request.mockImplementationOnce(() => pending.promise)
    await wrapper.find('.new-request').trigger('submit'); await wrapper.find('.new-request').trigger('submit')
    expect(posts()).toHaveLength(1); pending.resolve(request()); await flushPromises()
  })
  it('keeps form data after failed submission with recovery guidance', async () => {
    const { wrapper } = setup(); await login(wrapper); await requestForm(wrapper)
    api.request.mockRejectedValueOnce(new Error('Process template changed'))
    await wrapper.find('.new-request').trigger('submit'); await flushPromises()
    expect(wrapper.find('[role=alert]').text()).toContain('Refresh requests before retrying')
    expect(wrapper.find('.new-request input[maxlength="120"]').element.value).toBe('Annual leave')
    expect(wrapper.find('.new-request button').attributes('disabled')).toBeUndefined()
  })
  it('clears account state on logout and ignores a stale submission response', async () => {
    const { wrapper } = setup(); await login(wrapper); await requestForm(wrapper); const pending = deferred()
    api.request.mockImplementationOnce(() => pending.promise)
    await wrapper.find('.new-request').trigger('submit'); await wrapper.find('[aria-label="Sign out"]').trigger('click')
    pending.resolve(request()); await flushPromises()
    expect(wrapper.find('.workspace').exists()).toBe(false); expect(wrapper.text()).not.toContain('Annual leave')
    expect(api.logout).toHaveBeenCalled()
  })
})

describe('sequential decisions and progress', () => {
  it('advances the exact current step without calling the whole request approved', async () => {
    const item = request(sequence); const { wrapper } = setup('bob', [item], sequence); await login(wrapper)
    await wrapper.find('.request-item').trigger('click'); await wrapper.find('.decision-form textarea').setValue('Reviewed')
    expect(wrapper.find('.decision-form button.primary').text()).toBe('Approve step')
    expect(wrapper.find('.next-step').text()).toContain('Next: Final review · Carol')
    api.request.mockResolvedValueOnce(decideResult(item, 'manager', 'bob', 'PENDING', 'finance', 'carol'))
    await wrapper.find('.decision-form').trigger('submit'); await flushPromises()
    expect(payload()).toEqual({ stepId: 'manager', decision: 'APPROVE', comment: 'Reviewed' })
    expect(wrapper.find('[role=status]').text()).toContain('Step approved. The request is still pending; Carol')
    expect(wrapper.find('.decision-form').exists()).toBe(false)
    expect(wrapper.find('.snapshot-steps [data-step-id="manager"]').text()).toContain('Approved')
    expect(wrapper.find('.snapshot-steps [data-step-id="finance"]').text()).toContain('Awaiting review')
    expect(wrapper.find('.timeline').text()).toContain('Manager review · approved')
    expect(wrapper.find('.detail .status').text()).toBe('pending')
  })
  it.each(['APPROVE', 'REJECT'])('records terminal %s for a captured step and removes decision controls', async decision => {
    const item = request(); const { wrapper } = setup('bob', [item]); await login(wrapper)
    await wrapper.find('.request-item').trigger('click'); await wrapper.find('.decision-form textarea').setValue('Reviewed')
    expect(wrapper.find('.decision-form button.primary').text()).toBe('Approve request')
    const result = decideResult(item, 'manager', 'bob', decision === 'APPROVE' ? 'APPROVED' : 'REJECTED', null, 'bob', decision)
    api.request.mockResolvedValueOnce(result)
    if (decision === 'APPROVE') await wrapper.find('.decision-form').trigger('submit')
    else await wrapper.find('.decision-form .danger').trigger('click')
    await flushPromises()
    expect(payload()).toEqual({ stepId: 'manager', decision, comment: 'Reviewed' })
    expect(wrapper.find('.decision-form').exists()).toBe(false)
    expect(wrapper.find('[role=status]').text()).toBe(`Request ${decision === 'APPROVE' ? 'approved' : 'rejected'}.`)
    expect(wrapper.find('.next-step').exists()).toBe(false)
  })
  it('shows remaining steps as not reached after a rejection', async () => {
    const item = decideResult(request(sequence), 'manager', 'bob', 'REJECTED', null, 'bob', 'REJECT')
    const { wrapper } = setup('alice', [item], sequence); await login(wrapper); await wrapper.find('.request-item').trigger('click')
    expect(wrapper.find('.snapshot-steps [data-step-id="manager"]').text()).toContain('Rejected')
    expect(wrapper.find('.snapshot-steps [data-step-id="finance"]').text()).toContain('Not reached')
    expect(wrapper.find('.snapshot-steps [data-step-id="end"]').text()).toContain('Not reached')
  })
  it('keeps repeated approvers as separate decisions with distinct step IDs', async () => {
    const sameApprover = { ...sequence, nodes: [start, manager, { ...finance, assigneeId: 'bob' }, end] }
    const item = request(sameApprover); const { wrapper } = setup('bob', [item], sameApprover); await login(wrapper)
    await wrapper.find('.request-item').trigger('click')
    const next = decideResult(item, 'manager', 'bob', 'PENDING', 'finance', 'bob')
    api.request.mockResolvedValueOnce(next); await wrapper.find('.decision-form').trigger('submit'); await flushPromises()
    expect(wrapper.find('.decision-form').exists()).toBe(true)
    expect(wrapper.find('.decision-context').text()).toContain('Final review')
    expect(wrapper.find('.decision-form button.primary').text()).toBe('Approve request')
    api.request.mockResolvedValueOnce(decideResult(next, 'finance', 'bob', 'APPROVED', null, 'bob'))
    await wrapper.find('.decision-form').trigger('submit'); await flushPromises()
    expect(posts().map(([, options]) => JSON.parse(options.body).stepId)).toEqual(['manager', 'finance'])
    expect(wrapper.findAll('.snapshot-steps li.approved')).toHaveLength(2)
  })
  it.each(['alice', 'carol'])('does not let %s decide a step assigned to Bob', async identity => {
    const { wrapper } = setup(identity, [request(sequence)], sequence); await login(wrapper); await wrapper.find('.request-item').trigger('click')
    expect(wrapper.find('.decision-form').exists()).toBe(false)
    expect(wrapper.text()).toContain('Only the designated approver for the current step')
  })
  it('suppresses repeated decisions and preserves pending data on an error', async () => {
    const { wrapper } = setup('bob', [request()]); await login(wrapper); await wrapper.find('.request-item').trigger('click')
    await wrapper.find('.decision-form textarea').setValue('Keep comment'); const pending = deferred()
    api.request.mockImplementationOnce(() => pending.promise)
    await wrapper.find('.decision-form').trigger('submit'); await wrapper.find('.decision-form').trigger('submit')
    expect(posts()).toHaveLength(1)
    pending.reject(new Error('Step is no longer current')); await flushPromises()
    expect(wrapper.find('[role=alert]').text()).toContain('Refresh to check the latest status')
    expect(wrapper.find('.decision-form textarea').element.value).toBe('Keep comment')
    expect(wrapper.find('.detail .status').text()).toBe('pending')
  })
  it('clears old step comments when refresh advances the same approver to another step', async () => {
    const sameApprover = { ...sequence, nodes: [start, manager, { ...finance, assigneeId: 'bob' }, end] }
    const item = request(sameApprover); const { wrapper, server } = setup('bob', [item], sameApprover)
    await login(wrapper); await wrapper.find('.request-item').trigger('click'); await wrapper.find('.decision-form textarea').setValue('Old step comment')
    server.items = [decideResult(item, 'manager', 'bob', 'PENDING', 'finance', 'bob')]
    await button(wrapper, 'refresh').trigger('click'); await flushPromises()
    expect(wrapper.find('.decision-form textarea').element.value).toBe('')
    api.request.mockResolvedValueOnce(decideResult(server.items[0], 'finance', 'bob', 'APPROVED', null, 'bob'))
    await wrapper.find('.decision-form').trigger('submit'); await flushPromises()
    expect(payload().stepId).toBe('finance')
  })
  it('preserves newer selection while an earlier decision resolves', async () => {
    const item = request(), other = request(blueprint, { id: 'r2', title: 'Second request' })
    const { wrapper } = setup('bob', [item, other]); await login(wrapper); await wrapper.findAll('.request-item')[0].trigger('click')
    const pending = deferred(); api.request.mockImplementationOnce(() => pending.promise)
    await wrapper.find('.decision-form').trigger('submit'); await wrapper.findAll('.request-item')[1].trigger('click')
    pending.resolve(decideResult(item, 'manager', 'bob', 'APPROVED', null, 'bob')); await flushPromises()
    expect(wrapper.find('.detail h2').text()).toBe('Second request')
    expect(wrapper.find('.detail .status').text()).toBe('pending')
    expect(posts()[0][0]).toBe('/requests/r1/decisions')
  })
  it('ignores decision and refresh responses after logout', async () => {
    const { wrapper } = setup('bob', [request()]); await login(wrapper); await wrapper.find('.request-item').trigger('click')
    const pending = deferred(); api.request.mockImplementationOnce(() => pending.promise)
    await wrapper.find('.decision-form').trigger('submit'); await wrapper.find('[aria-label="Sign out"]').trigger('click')
    pending.resolve(decideResult(request(), 'manager', 'bob', 'APPROVED', null, 'bob')); await flushPromises()
    expect(wrapper.find('.workspace').exists()).toBe(false); expect(wrapper.text()).not.toContain('Request approved.')
    await login(wrapper); const refreshed = deferred(); api.request.mockImplementationOnce(() => refreshed.promise)
    await button(wrapper, 'refresh').trigger('click'); await wrapper.find('[aria-label="Sign out"]').trigger('click')
    refreshed.resolve([request()]); await flushPromises()
    expect(wrapper.find('.workspace').exists()).toBe(false)
  })
})

describe('malformed template recovery', () => {
  it('rejects a malformed template at login without rendering an unsafe workspace', async () => {
    const { wrapper } = setup('alice', [], { ...blueprint, nodes: [null] }); await login(wrapper)
    expect(wrapper.find('.workspace').exists()).toBe(false)
    expect(wrapper.find('[role=alert]').text()).toContain('Invalid process template')
    expect(api.logout).toHaveBeenCalled()
  })
  it('preserves the usable template and local draft if refresh returns malformed data', async () => {
    const { wrapper, server } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue('Keep this draft')
    server.definition = { ...blueprint, nodes: {} }
    await button(wrapper, 'refresh').trigger('click'); await flushPromises()
    expect(button(wrapper, 'process-name').element.value).toBe('Keep this draft')
    expect(wrapper.find('[role=alert]').text()).toContain('Invalid process template')
    expect(wrapper.text()).toContain('Published v1')
  })
})

const parallel = (mode = 'ALL', version = 2) => ({ ...clone(blueprint), schemaVersion: 3, version, nodes: [start, { id: 'team', type: 'parallelApproval', name: 'Team review', assigneeId: null, assigneeIds: ['bob', 'carol'], completionMode: mode }, finance, end] })
const groupRequest = (mode = 'ALL', overrides = {}) => request(parallel(mode), { currentStepId: 'team', ...overrides })
const groupVote = (actorId, action) => ({ actorId, action, stepId: 'team', comment: `${actorId} saved comment`, at: '2026-10-04T12:00:00Z' })
describe('parallel process designer and participant views', () => {
  it('converts a local single step to ALL then ANY and publishes its exact group shape', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await wrapper.find('[aria-label="Step 1 review mode"]').setValue('ALL')
    expect(wrapper.find('[aria-label="Step 1 approver"]').exists()).toBe(false)
    expect(wrapper.find('[aria-label="Step 1 participant Bob"]').element.checked).toBe(true)
    expect(wrapper.find('[aria-label="Step 1 participant Carol"]').element.checked).toBe(true)
    expect(wrapper.text()).toContain('ALL: every participant must approve')
    expect(posts()).toHaveLength(0)
    await wrapper.find('[aria-label="Step 1 review mode"]').setValue('ANY')
    expect(wrapper.text()).toContain('Rejection ends the request only after every participant rejects')
    const published = { ...clone(blueprint), schemaVersion: 3, version: 2, nodes: [start, { ...manager, type: 'parallelApproval', assigneeId: null, assigneeIds: ['bob', 'carol'], completionMode: 'ANY' }, end] }
    api.request.mockResolvedValueOnce(published)
    await button(wrapper, 'publish').trigger('click'); await flushPromises()
    expect(payload()).toEqual({ expectedVersion: 1, definition: { ...published, version: 1 } })
    expect(wrapper.text()).toContain('Published v2')
    expect(JSON.parse(wrapper.find('.designer-json pre').text()).schemaVersion).toBe(3)
  })
  it('blocks missing participants, keeps changes across navigation, and resets without posting', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await wrapper.find('[aria-label="Step 1 review mode"]').setValue('ALL')
    await wrapper.find('[aria-label="Step 1 participant Carol"]').setValue(false)
    expect(wrapper.find('.validation-list').text()).toContain('at least two distinct participants')
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
    await wrapper.find('nav button').trigger('click'); await designer(wrapper)
    expect(wrapper.find('[aria-label="Step 1 participant Carol"]').element.checked).toBe(false)
    await wrapper.find('[aria-label="Step 1 participant Carol"]').setValue(true)
    expect(button(wrapper, 'publish').attributes('disabled')).toBeUndefined()
    await button(wrapper, 'reset-draft').trigger('click')
    expect(wrapper.find('[aria-label="Step 1 review mode"]').element.value).toBe('SINGLE')
    expect(wrapper.find('.participant-picker').exists()).toBe(false)
    expect(posts()).toHaveLength(0)
  })
  it('converts back to single with no stale group fields', async () => {
    const { wrapper } = setup('alice', [], parallel()); await login(wrapper); await designer(wrapper)
    await wrapper.find('[aria-label="Step 1 review mode"]').setValue('SINGLE')
    const expected = { ...parallel(), nodes: [start, { id: 'team', type: 'approval', name: 'Team review', assigneeId: 'bob' }, finance, end] }
    api.request.mockResolvedValueOnce({ ...expected, version: 3 })
    await button(wrapper, 'publish').trigger('click'); await flushPromises()
    expect(payload().definition).toEqual(expected)
  })
  it('reloads published ALL/ANY definitions and keeps non-editors read-only', async () => {
    const { wrapper } = setup('carol', [], parallel('ANY')); await login(wrapper); await designer(wrapper)
    expect(wrapper.text()).toContain('Any one approves (ANY)'); expect(wrapper.text()).toContain('Assigned to Bob + Carol')
    expect(wrapper.find('.participant-picker, .step-inspector select, .step-inspector input').exists()).toBe(false)
    expect(button(wrapper, 'publish').exists()).toBe(false)
  })
  it('preserves a group draft after conflict and prevents a repeated in-flight publish', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await wrapper.find('[aria-label="Step 1 review mode"]').setValue('ANY')
    const pending = deferred(); api.request.mockImplementationOnce(() => pending.promise)
    await button(wrapper, 'publish').trigger('click'); await button(wrapper, 'publish').trigger('click')
    expect(posts()).toHaveLength(1)
    expect(wrapper.find('[aria-label="Step 1 review mode"]').attributes('disabled')).toBeDefined()
    expect(wrapper.find('.participant-picker').attributes('disabled')).toBeDefined()
    pending.reject(Object.assign(new Error('Stale version'), { status: 409 })); await flushPromises()
    expect(wrapper.find('[aria-label="Step 1 review mode"]').element.value).toBe('ANY')
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
    expect(wrapper.find('[role=alert]').text()).toContain('Your draft is preserved')
  })
  it('allows every pending group member, including Carol when approverId is Bob', async () => {
    const { wrapper } = setup('carol', [groupRequest()], parallel()); await login(wrapper)
    expect(wrapper.findAll('nav button')[1].text()).toContain('1')
    await wrapper.find('.request-item').trigger('click')
    expect(wrapper.find('.decision-form').exists()).toBe(true)
    expect(wrapper.find('.decision-form button.primary').text()).toBe('Approve vote')
    expect(wrapper.find('.participant-votes').text()).toContain('Bob · Awaiting vote')
    expect(wrapper.find('.participant-votes').text()).toContain('Carol · Awaiting vote')
    expect(wrapper.find('dl').text()).toContain('Bob, Carol')
  })
  it.each([['ALL', 'APPROVE'], ['ANY', 'REJECT']])('keeps %s pending after Bob votes %s and removes his action', async (mode, decision) => {
    const item = groupRequest(mode), { wrapper } = setup('bob', [item], parallel(mode)); await login(wrapper)
    await wrapper.find('.request-item').trigger('click')
    api.request.mockResolvedValueOnce({ ...item, approverId: 'carol', history: [...item.history, groupVote('bob', decision)] })
    if (decision === 'APPROVE') await wrapper.find('.decision-form').trigger('submit'); else await wrapper.find('.decision-form .danger').trigger('click')
    await flushPromises()
    expect(payload().stepId).toBe('team')
    expect(wrapper.find('[role=status]').text()).toBe('Vote recorded. This group is still pending; awaiting Carol.')
    expect(wrapper.find('.snapshot-steps [data-step-id="team"]').classes()).toContain('current')
    expect(wrapper.find('.participant-votes').text()).toContain(`Bob · ${decision === 'APPROVE' ? 'Approved' : 'Rejected'}`)
    expect(wrapper.find('.participant-votes').text()).toContain('bob saved comment')
    expect(wrapper.find('.decision-form').exists()).toBe(false)
    expect(wrapper.findAll('nav button')[1].text()).toContain('0')
  })
  it.each([['ALL', 'REJECT', 'REJECTED'], ['ANY', 'APPROVE', 'APPROVED']])('shows %s early outcome and remaining votes not required', async (mode, decision, status) => {
    const definition = parallel(mode); definition.nodes.splice(2, 1)
    const item = request(definition, { status, currentStepId: null, history: [groupVote('bob', decision)] })
    const { wrapper } = setup('carol', [item], definition); await login(wrapper); await wrapper.find('.request-item').trigger('click')
    expect(wrapper.find('.participant-votes').text()).toContain('Carol · Not required')
    expect(wrapper.find('.decision-form').exists()).toBe(false)
    expect(wrapper.find('.snapshot-steps [data-step-id="team"]').classes()).toContain(status.toLowerCase())
  })
  it('blocks self-submission for any participant in a later group', async () => {
    const { wrapper } = setup('bob', [], parallel()); await login(wrapper); await requestForm(wrapper)
    expect(wrapper.find('.new-request button').attributes('disabled')).toBeDefined()
    await wrapper.find('.new-request').trigger('submit'); expect(posts()).toHaveLength(0)
  })
  it('rejects a malformed duplicate-participant template without rendering', async () => {
    const d = parallel(); d.nodes[1].assigneeIds = ['bob', 'bob']
    const { wrapper } = setup('alice', [], d); await login(wrapper)
    expect(wrapper.find('.workspace').exists()).toBe(false)
    expect(wrapper.find('[role=alert]').text()).toContain('distinct participants')
  })
})

describe('workbench history and publication boundaries', () => {
  it('keeps local undo across navigation and never turns undo into a publication', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await wrapper.find('[aria-label="Step 1 review mode"]').setValue('ANY')
    await wrapper.find('nav button').trigger('click'); await designer(wrapper)
    expect(button(wrapper, 'undo').attributes('disabled')).toBeUndefined()
    await button(wrapper, 'undo').trigger('click')
    expect(wrapper.find('[aria-label="Step 1 review mode"]').element.value).toBe('SINGLE')
    expect(posts()).toHaveLength(0)
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
  })
  it('clears draft undo after confirmed publication and does not roll back the published version', async () => {
    const { wrapper } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue('Published title')
    expect(button(wrapper, 'undo').attributes('disabled')).toBeUndefined()
    api.request.mockResolvedValueOnce({ ...clone(blueprint), name:'Published title', version:2 })
    await button(wrapper, 'publish').trigger('click'); await flushPromises()
    expect(button(wrapper, 'undo').attributes('disabled')).toBeDefined()
    await button(wrapper, 'undo').trigger('click')
    expect(button(wrapper, 'process-name').element.value).toBe('Published title')
    expect(wrapper.text()).toContain('Published v2')
    expect(posts()).toHaveLength(1)
  })
  it('restores an old draft after reset without letting it publish over a newer version', async () => {
    const { wrapper, server } = setup(); await login(wrapper); await designer(wrapper)
    await button(wrapper, 'process-name').setValue('Original unsaved draft')
    server.definition = { ...clone(blueprint), name:'Newer publication', version:2 }
    await button(wrapper, 'refresh').trigger('click'); await flushPromises()
    await button(wrapper, 'reset-draft').trigger('click')
    expect(button(wrapper, 'process-name').element.value).toBe('Newer publication')
    await button(wrapper, 'undo').trigger('click')
    expect(button(wrapper, 'process-name').element.value).toBe('Original unsaved draft')
    expect(button(wrapper, 'stale-draft').exists()).toBe(true)
    expect(button(wrapper, 'publish').attributes('disabled')).toBeDefined()
    expect(posts()).toHaveLength(0)
  })
})
