<script setup>
import { computed, onUnmounted, ref, watch } from 'vue'
import ProcessDesigner from '../ProcessDesigner.vue'
import UiIcon from '../UiIcon.vue'
import { approvalNodes, participants, pendingParticipants } from '../process.js'
import { createScenarioApi } from './scenario-api.js'
import { createScenarioWorkspace } from './scenario-workspace.js'
import { RECEIVING_ID, receivingErrors } from './receiving-document.js'
import ReceivingForm from './ReceivingForm.vue'
import ScenarioDetail from './ScenarioDetail.vue'
const props = defineProps({ api: { type: Object, default: null } })
const workspace = createScenarioWorkspace(props.api || createScenarioApi(), undefined, RECEIVING_ID), s = workspace.state
const locale = ref('en'), username = ref('alice'), password = ref('')
const zh = computed(() => locale.value === 'zh')
watch(locale, value => { document.documentElement.lang = value === 'zh' ? 'zh-CN' : 'en' }, { immediate: true })
onUnmounted(() => workspace.dispose())
const template = computed(() => s.catalog.find(entry => entry.id === RECEIVING_ID))
const name = id => { const person = s.people.find(person => person.id === id); return person?.displayName || person?.name || id }
const selected = computed(() => s.items.find(view => view.request.id === s.selectedId))
const mine = computed(() => s.items.filter(view => view.request.applicantId === s.me?.id))
const review = computed(() => s.items.filter(view => pendingParticipants(view.request).includes(s.me?.id)))
const handled = computed(() => s.items.filter(view => view.request.history.some(event => event.actorId === s.me?.id && ['APPROVE', 'REJECT'].includes(event.action))))
const retained = computed(() => s.items.filter(view => workspace.retainedNotesFor(view.request.id).length))
const retainedCount = computed(() => Object.keys(s.retainedNotes).length)
const visible = computed(() => s.tab === 'retained' ? retained.value : s.tab === 'review' ? review.value : s.tab === 'handled' ? handled.value : mine.value)
const status = value => ({ PENDING: zh.value ? '审批中' : 'Pending', APPROVED: zh.value ? '已通过' : 'Approved', REJECTED: zh.value ? '已驳回' : 'Rejected' })[value]
const tabs = computed(() => [
  { id: 'new', label: zh.value ? '新建收货单' : 'New receipt', icon: 'requests' },
  { id: 'mine', label: zh.value ? '我的收货单' : 'My receipts', icon: 'requests', count: mine.value.length },
  { id: 'review', label: zh.value ? '待我审批' : 'Needs my review', icon: 'review', count: review.value.length },
  { id: 'handled', label: zh.value ? '我的审批记录' : 'My decisions', icon: 'review', count: handled.value.length },
  ...(retained.value.length ? [{ id: 'retained', label: zh.value ? '保留的说明' : 'Retained notes', icon: 'requests', count: retained.value.length }] : []),
  { id: 'designer', label: zh.value ? '审批流程' : 'Approval process', icon: 'process' },
])
const currentTitle = computed(() => tabs.value.find(tab => tab.id === s.tab)?.label)
function navigate(tab) { s.tab = tab; s.selectedId = null; s.comment = '' }
function openRetained() { navigate('retained'); if (retained.value.length) workspace.select(retained.value[0].request.id) }
function dismissNote(id, stepId) {
  workspace.dismissRetainedNote(id, stepId)
  if (s.tab === 'retained' && !workspace.retainedNotesFor(id).length) {
    if (retained.value.length) workspace.select(retained.value[0].request.id)
    else navigate('review')
  }
}
async function login() {
  if (s.busy) return
  const secret = password.value; password.value = ''
  await workspace.login(username.value, secret)
  if (s.me) navigate(s.me.id === 'alice' ? 'new' : 'review')
}
const errorText = computed(() => {
  if (!s.error) return ''
  if (['DECISION_COMMENT_MISMATCH', 'DECISION_RECOVERY_MISMATCH'].includes(s.error.cause?.code)) return zh.value ? '保存的审批记录未确认本次意见与说明。说明已保留在原节点，请更新数据核对后再继续。' : 'Saved activity did not confirm this decision and note. Your note is retained with its original stage. Refresh and inspect the audit before continuing.'
  const en = { login: 'Sign-in could not be completed. Check the account, server-configured password and backend, then try again.', validation: 'Check the highlighted fields and quantity reconciliation before submitting.', selfAssigned: 'An applicant cannot review their own receipt. Alice can adjust the published process.', refresh: 'Refresh failed. Existing records and local edits are preserved. Try Refresh again.', publish: 'Publication was not confirmed. Your draft is preserved. Refresh, reset to the latest process, and reapply your edits before publishing.', submit: s.rejectedVersion ? 'The published process changed. Refresh before submitting.' : 'Submission was not confirmed. Check My receipts, or retry the unchanged form with its original key and process version. Editing starts a new request intent.', decision: 'The decision was not confirmed. We checked for saved results. If actions remain locked, refresh before deciding again.' }
  const cn = { login: '登录未完成。请检查账号、服务端密码与后端服务，再重试。', validation: '请检查高亮字段与数量核对结果，再提交。', selfAssigned: '申请人不能审批自己的收货单。Alice 可调整已发布流程。', refresh: '数据更新失败，现有记录与本地修改已保留。请重试。', publish: '发布结果未确认，草稿已保留。请更新数据，重置为最新流程，再重新应用修改后发布。', submit: s.rejectedVersion ? '已发布流程发生变化，请更新数据后再提交。' : '提交结果未确认。请检查我的收货单，或保持表单不变，以原标识与流程版本重试。修改表单会创建新的申请意图。', decision: '审批结果未确认，已尝试读取保存结果。如操作仍被锁定，请先更新数据。' }
  return (zh.value ? cn : en)[s.error.operation] || (zh.value ? '操作失败，请重试。' : 'The operation failed. Try again.')
})
const noticeText = computed(() => ({ refreshed: zh.value ? '数据已更新，本地修改已保留。' : 'Data refreshed. Local edits are preserved.', submitted: zh.value ? '收货单已保存，审批流程已启动。' : 'Receipt saved. Its approval process has started.', published: zh.value ? `流程 v${s.process?.version} 已发布，已提交收货单保留原快照。` : `Process v${s.process?.version} published. Submitted receipts keep their snapshots.`, decided: zh.value ? '审批意见已保存。' : 'Your decision is saved.' })[s.notice])
const scopeNote = computed(() => zh.value ? '仅本地合成数据。不查询真实采购单，不核算跨单累计数量，不增加库存，不付款，也不回写外部系统。' : 'Local synthetic data only. No real purchase order lookup, cumulative quantities across receipts, stock posting, payment or external writeback.')
const rolesNote = computed(() => zh.value ? '默认演示流程中，Bob 兼任仓库验收与采购复核，Carol 参与质量验收。实际分配以所示流程为准；没有动态角色分配或职责分离保证。' : 'In the default sample route, Bob serves both warehouse inspection and procurement review; Carol participates in quality inspection. The displayed process defines actual assignments. No dynamic role assignment or separation-of-duties guarantee.')
</script>
<template>
  <div v-if="!s.me" class="sf-login rf-login" :lang="zh ? 'zh-CN' : 'en'">
    <section class="sf-login-story"><div class="wordmark"><span class="logo">a</span>ArcFlow<span class="sf-product-tag">ERP / RECEIVING</span></div><div><p class="sf-kicker">{{ zh ? '每一批到货，核对清楚' : 'EVERY DELIVERY. ACCOUNTED FOR.' }}</p><h1>{{ zh ? '收货有据，' : 'Receive with' }}<br>{{ zh ? '验收有序。' : 'confidence.' }}</h1><p>{{ zh ? '从采购单引用到逐行数量核对，让仓库、质量与采购在同一份收货快照中协作。' : 'From purchase order references to line-by-line reconciliation. Give warehouse, quality and procurement one clear receiving record.' }}</p><div class="rf-login-document" aria-hidden="true"><span>GRN / SAMPLE</span><strong>78 <small>ACCEPTED PCS</small></strong><div><span>80 RECEIVED</span><span>2 REJECTED</span></div><i>✓ 78 + 2 = 80</i></div></div><small>{{ scopeNote }}</small></section>
    <section class="sf-login-panel"><label class="sf-language"><span class="sr-only">Language / 语言</span><select v-model="locale" aria-label="Language / 语言"><option value="en">English</option><option value="zh">中文</option></select></label><form class="sf-login-form" @submit.prevent="login"><p class="sf-kicker">{{ zh ? '采购收货验收' : 'PURCHASE ORDER RECEIVING' }}</p><h2>{{ zh ? '进入收货工作台' : 'Open receiving workspace' }}</h2><p class="muted">{{ zh ? '使用服务端配置的演示账号与密码。' : 'Use a demo account and its server-configured password.' }}</p><label>{{ zh ? '演示账号' : 'Demo account' }}<select v-model="username" :disabled="s.busy"><option value="alice">Alice · {{ zh ? '申请人 / 流程管理员' : 'Applicant / process editor' }}</option><option value="bob">Bob · {{ zh ? '仓库 / 采购复核' : 'Warehouse / procurement' }}</option><option value="carol">Carol · {{ zh ? '质量验收' : 'Quality inspection' }}</option></select></label><label>{{ zh ? '密码' : 'Password' }}<input v-model="password" type="password" autocomplete="off" :disabled="s.busy" required></label><p v-if="s.error" class="error" role="alert">{{ errorText }}</p><button class="primary full" type="submit" :disabled="s.busy">{{ s.busy ? (zh ? '正在登录…' : 'Signing in…') : (zh ? '进入工作台' : 'Open workspace') }} →</button><p class="sf-login-note">{{ zh ? '凭据仅保存在当前标签页内存中。退出或刷新网页会清除未保存草稿。' : 'Credentials stay in this tab’s memory. Sign-out or browser reload clears unsaved drafts.' }}</p><a class="rf-back-link" href="/scenarios.html">← {{ zh ? '场景库' : 'Scenario library' }}</a></form></section>
  </div>
  <div v-else class="sf-shell rf-shell" :lang="zh ? 'zh-CN' : 'en'">
    <aside class="sf-sidebar"><div class="wordmark"><span class="logo">a</span>ArcFlow</div><div class="sf-sidebar-title">ERP / {{ zh ? '收货验收' : 'RECEIVING' }}</div><nav :aria-label="zh ? '主导航' : 'Main navigation'"><button v-for="tab in tabs" :key="tab.id" :data-testid="`${tab.id}-tab`" :class="{ active: s.tab === tab.id }" @click="navigate(tab.id)"><UiIcon :name="tab.icon" />{{ tab.label }}<small v-if="tab.count !== undefined">{{ tab.count }}</small></button></nav><div class="sf-sidebar-bottom"><a class="rf-back-link" href="/scenarios.html">← {{ zh ? '场景库' : 'Scenario library' }}</a><p>{{ zh ? '计数仅代表当前用户已加载的记录。' : 'Counts reflect loaded records for this account.' }}</p><span class="sf-synthetic-dot"></span><span>{{ zh ? '合成数据工作空间' : 'Synthetic workspace' }}</span></div><div class="sf-person"><span>{{ name(s.me.id).charAt(0) }}</span><div><strong>{{ name(s.me.id) }}</strong><small>{{ s.me.id === 'alice' ? (zh ? '申请人 · 管理员' : 'Applicant · editor') : (zh ? '审批人' : 'Reviewer') }}</small></div><button type="button" :aria-label="zh ? '退出登录' : 'Sign out'" data-testid="receiving-logout" @click="workspace.logout"><UiIcon name="logout" /></button></div></aside>
    <main class="sf-main"><header class="sf-topbar"><div><span>ERP</span><i>/</i><strong>{{ currentTitle }}</strong></div><div class="sf-topbar-actions"><label class="sf-language"><span class="sr-only">Language / 语言</span><select v-model="locale" aria-label="Language / 语言"><option value="en">English</option><option value="zh">中文</option></select></label><button class="secondary" data-testid="receiving-refresh" :disabled="s.busy" @click="workspace.refresh">↻ <span>{{ zh ? '更新数据' : 'Refresh' }}</span></button><button class="secondary sf-mobile-logout" type="button" :aria-label="zh ? '退出登录' : 'Sign out'" @click="workspace.logout"><UiIcon name="logout" /></button></div></header>
      <div class="sf-content"><div v-if="s.error" class="error sf-alert" role="alert"><strong>{{ errorText }}</strong><details v-if="s.error.cause?.message"><summary>{{ zh ? '原始服务信息' : 'Original service detail' }}</summary>{{ s.error.cause.message }}</details></div><p v-if="s.notice" class="notice" role="status">{{ noticeText }}</p><button v-if="retainedCount" type="button" class="sf-retained-index" data-testid="retained-notes-summary" @click="openRetained">{{ retainedCount }} {{ zh ? '条未确认说明已保留，点击查看' : 'unconfirmed notes retained. Review notes' }} →</button>
        <template v-if="s.tab === 'new'"><div class="sf-page-title sf-title-row"><div><p class="sf-kicker">ERP / {{ zh ? '采购收货验收' : 'PURCHASE ORDER RECEIVING' }}</p><h1>{{ zh ? '让到货数量，对得上。' : 'Every unit, accounted for.' }}</h1><p>{{ zh ? '记录本次到货、合格与不合格数量，再交给审批人复核。' : 'Record this delivery, reconcile accepted and rejected goods, then send it for review.' }}</p></div><span class="rf-warehouse-badge">▥ {{ zh ? '收货工作台' : 'RECEIVING DESK' }}<small>{{ zh ? '表单' : 'FORM' }} v{{ template.formVersion }}</small></span></div><p v-if="s.uncertainSubmission" class="warning">{{ zh ? '上次提交结果不确定，原提交标识已保留。修改表单前，请先检查我的收货单。' : 'The last submission is uncertain. Its retry key is retained. Check My receipts before editing.' }}</p><div class="sf-create-layout"><ReceivingForm :template="template" :model-value="s.form" :locale="locale" :errors="receivingErrors(s.form)" :attempted="s.attempted" :busy="s.busy" :retrying="s.uncertainSubmission" :rejected-version="s.rejectedVersion" @update:model-value="workspace.setForm" @submit="workspace.submit" /><aside class="sf-context-card rf-context"><p class="sf-kicker">{{ zh ? '本次收货的审批路径' : 'THIS RECEIPT’S ROUTE' }}</p><h2>{{ zh ? '验收之后，逐步复核。' : 'Inspect. Review. Record.' }}</h2><ol class="sf-mini-flow"><li class="sf-mini-start"><span>↗</span><div><strong>{{ name(s.me.id) }}</strong><small>{{ zh ? '提交收货单' : 'Submits the receipt' }}</small></div></li><li v-for="(node, index) in approvalNodes(workspace.submissionDefinition())" :key="node.id"><span>{{ index + 1 }}</span><div><strong>{{ node.name }}</strong><small>{{ participants(node).map(name).join(' + ') }}<template v-if="node.completionMode"> · {{ node.completionMode }}</template></small></div></li><li class="sf-mini-end"><span>✓</span><div><strong>{{ zh ? '审批完成' : 'Review complete' }}</strong><small>{{ zh ? '保留验收与审批记录' : 'Inspection and decision trail retained' }}</small></div></li></ol><div class="sf-context-note"><strong>{{ zh ? '流程快照' : 'Process snapshot' }} v{{ workspace.submissionDefinition()?.version }}</strong><p>{{ zh ? '业务与流程在提交时一起保存，之后发布的新流程不会改动本单。' : 'The document and process are saved together. Later process publications do not change this receipt.' }}</p></div><p class="rf-roles-note">{{ rolesNote }}</p><p class="sf-local-note">{{ scopeNote }}</p></aside></div></template>
        <section v-if="['mine', 'review', 'handled', 'retained'].includes(s.tab)"><div class="sf-page-title sf-title-row"><div><p class="sf-kicker">ERP / {{ zh ? '收货记录' : 'RECEIVING RECORDS' }}</p><h1>{{ currentTitle }}</h1><p>{{ s.tab === 'review' ? (zh ? '当前阶段仍需要你审批的收货单。' : 'Receipts that still need your decision on the current stage.') : s.tab === 'handled' ? (zh ? '已保存你的审批意见；同一人可能在后续节点再次审批。' : 'Receipts with your saved decisions. The same person can review again at a later stage.') : s.tab === 'retained' ? (zh ? '说明保留在原申请与原节点中，退出登录时会清除。' : 'Notes stay with their original receipt and stage. Sign-out clears them.') : (zh ? '逐行查看收货快照与最新审批状态。' : 'Inspect saved receiving lines and their latest approval state.') }}</p></div><button v-if="s.tab === 'mine'" class="primary" @click="navigate('new')">＋ {{ zh ? '新建收货单' : 'New receipt' }}</button></div><div class="sf-record-layout"><section class="sf-request-list" :aria-label="currentTitle"><header><strong>{{ visible.length }} {{ zh ? '条已加载记录' : 'loaded records' }}</strong></header><div v-if="!visible.length" class="sf-empty"><UiIcon name="requests" /><h2>{{ zh ? '目前没有收货单' : 'No receipts here yet' }}</h2><p>{{ zh ? '相关收货单会显示在这里。' : 'Relevant receiving records will appear here.' }}</p></div><button v-for="view in visible" :key="view.request.id" class="sf-request-item" :class="{ selected: s.selectedId === view.request.id }" :aria-pressed="s.selectedId === view.request.id" @click="workspace.select(view.request.id)"><div><span class="sf-status" :class="view.request.status.toLowerCase()">{{ status(view.request.status) }}</span><small>{{ view.request.business.businessId }}</small></div><strong>{{ view.request.title }}</strong><p>{{ view.request.business.purchaseOrderRef }} · {{ view.summary.lineCount }} {{ zh ? '行明细' : 'lines' }}</p><footer><b>{{ view.summary.quantities.map(row => `${row.received} ${row.unit}`).join(' · ') }}</b><span>→</span></footer><small class="rf-exception-label" v-if="view.summary.exceptionLineCount">{{ view.summary.exceptionLineCount }} {{ zh ? '行有不合格品' : 'lines with rejected goods' }}</small></button></section><ScenarioDetail v-if="selected" :view="selected" :template="template" :locale="locale" :people="s.people" v-model:comment="s.comment" :busy="s.busy" :can-decide="workspace.canDecide(selected)" :blocked="s.blockedDecisions.includes(selected.request.id)" :retained-notes="workspace.retainedNotesFor(selected.request.id)" @dismiss-note="dismissNote(selected.request.id, $event)" @decide="workspace.decide" /><div v-else class="sf-detail-placeholder"><div class="sf-placeholder-symbol">▥</div><h2>{{ zh ? '每一行收货，记录完整。' : 'A complete record of every line.' }}</h2><p>{{ zh ? '选择收货单，查看数量、异常原因与审批快照。' : 'Select a receipt to inspect quantities, exceptions and its saved approval process.' }}</p></div></div></section>
        <section v-show="s.tab === 'designer'" class="sf-designer-section"><div class="sf-page-title"><p class="sf-kicker">ERP / {{ zh ? '流程设计' : 'PROCESS DESIGN' }}</p><h1>{{ zh ? '从验收到复核，责任清晰。' : 'From inspection to sign-off.' }}</h1><p>{{ zh ? '有序阶段支持单人、ALL 或 ANY 审批。已提交收货单保留原流程快照。' : 'Ordered stages support single, ALL or ANY review. Submitted receipts keep their original process snapshot.' }}</p><p class="rf-roles-note">{{ rolesNote }}</p></div><ProcessDesigner v-if="s.draft" v-model="s.draft" :published="s.process" :expected-process-id="RECEIVING_ID" :people="s.people" :editable="s.me.id === 'alice'" :busy="s.busy" :publishing="s.publishing" :dirty="workspace.dirty()" :stale="workspace.stale()" :initial-locale="locale" :show-language="false" @publish="workspace.publish" @reset="workspace.resetDraft" /></section>
        <footer class="sf-workspace-footer rf-footer"><span>ArcFlow · ERP</span><span>{{ scopeNote }}</span></footer>
      </div>
    </main>
  </div>
</template>
