export const copy = {
  zh: {
    brand: "弧流",
    product: "移动审批",
    demo: "本机审批演示",
    demoNote:
      "使用服务端配置的 Alice、Bob 或 Carol 演示账号。请勿输入真实人事或健康信息。",
    welcome: "在手机上查看和处理审批。",
    loginHint: "登录后查看与你相关的申请。审批意见与处理记录由服务端保存。",
    username: "演示账号",
    password: "本地配置的密码",
    signIn: "进入工作台",
    signing: "正在验证…",
    signOut: "退出",
    identity: "当前身份",
    language: "English",
    loadFailed: "未能加载完整的申请列表",
    loadFailedBody: "未能加载最新申请，暂时无法确认是否有待办。请刷新后重试。",
    inbox: "审批工作台",
    eyebrow: "ARCFLOW / WORKSPACE",
    subtitle: "查看待你审批的申请和已经处理的记录。",
    todo: "待我审批",
    done: "我已处理",
    all: "与我相关",
    search: "搜索标题、原因或申请人",
    refresh: "刷新",
    refreshing: "正在同步…",
    loading: "正在获取审批记录…",
    emptyTitle: "这里暂时没有申请",
    emptyBody: "可以切换列表或换个关键词搜索。请在桌面端发起申请；移动端可以查看和审批。",
    emptyTodo: "当前没有待你审批的申请",
    emptyTodoBody:
      "已投票的会签申请可在「我已处理」继续追踪，最终结果以申请状态为准。",
    count: "项",
    pending: "审批中",
    approved: "已通过",
    rejected: "已驳回",
    applicant: "申请人",
    days: "天",
    duration: "请假时长",
    submitted: "发起时间",
    updated: "最后更新",
    requestType: "请假申请",
    back: "返回列表",
    details: "申请详情",
    reason: "申请事由",
    record: "审批记录",
    process: "流程概览",
    readonly: "只读 · 发起时的流程版本",
    version: "版本",
    current: "当前节点",
    approve: "同意",
    reject: "驳回",
    reviewApprove: "确认同意",
    reviewReject: "确认驳回",
    opinion: "审批意见（选填）",
    opinionHint: "审批意见会和本次处理结果一起保存，提交后不能在这里修改。",
    placeholder: "写下你的判断依据…",
    cancel: "取消",
    confirm: "确认提交",
    submitting: "正在提交…",
    singleConsequence:
      "同意将进入下一节点；若这是最后一步，申请将通过。驳回将结束本次申请。",
    allConsequence:
      "会签：所有成员同意后进入下一节点；任一成员驳回即结束申请。",
    anyConsequence:
      "或签：任一成员同意即进入下一节点；只有所有成员驳回才结束申请。",
    saved: "你的审批决定已保存",
    savedPending: "申请仍在审批中，可在「我已处理」追踪后续。",
    savedTerminal: "申请已结束。下面是最新状态和审批记录。",
    noAction: "当前无法审批",
    noActionBody: "你可能已经处理过这一步、还没轮到你审批，或申请已经结束。",
    missingTitle: "无法查看这条申请",
    missingBody: "申请不存在，或当前账号没有查看权限。",
    submitEvent: "发起申请",
    approveEvent: "同意",
    rejectEvent: "驳回",
    noComment: "未填写意见",
    allMode: "会签 · 全员同意",
    anyMode: "或签 · 任一同意",
    singleMode: "单人审批",
    completed: "已完成",
    upcoming: "待流转",
    skipped: "未执行",
    votePending: "待投票",
    notNeeded: "无需再投票",
    platformTitle: "尚未接入企业平台",
    platformBody:
      "还没有接入飞书、企业微信和钉钉的登录及消息功能。这个入口不能使用演示账号，请改用本机浏览器演示入口。",
    platformFoot: "尚未接入飞书、企业微信或钉钉的登录和消息功能",
    localOnly: "H5 本地演示",
    clearSearch: "清空搜索",
    retry: "重试",
    errors: {
      credentials: "账号或密码不正确，请检查本地后端配置。",
      expired: "身份验证已失效，请重新登录。审批记录保存在后端。",
      forbidden: "权限已变化。已尝试刷新状态，请核对后再操作。",
      missing: "当前账号无法访问这条申请。",
      conflict: "这条申请已有新的处理结果。请查看最新记录后再决定。",
      unavailable: "服务暂时不可用。尚未确认变更，请刷新核对后重试。",
      network:
        "连接中断，尚未确认变更。已尝试刷新；恢复连接后请核对记录再重试。",
      commentLong: "审批意见最多 2000 个字符。",
    },
  },
  en: {
    brand: "ArcFlow",
    product: "Mobile approvals",
    demo: "Local approval demo",
    demoNote:
      "Use the Alice, Bob or Carol demo account configured on your server. Do not enter real personnel or health information.",
    welcome: "Review requests on your phone.",
    loginHint:
      "Sign in to see requests relevant to you. Decision notes and history are saved by the server.",
    username: "Demo account",
    password: "Locally configured password",
    signIn: "Open workspace",
    signing: "Verifying…",
    signOut: "Sign out",
    identity: "Signed in as",
    language: "中文",
    loadFailed: "Could not load the full request list",
    loadFailedBody:
      "We couldn’t load the latest requests, so we can’t tell whether anything is waiting for you. Try refreshing.",
    inbox: "Approval workspace",
    eyebrow: "ARCFLOW / WORKSPACE",
    subtitle: "See requests waiting for you and decisions you have already made.",
    todo: "To review",
    done: "My decisions",
    all: "Related to me",
    search: "Search title, reason or applicant",
    refresh: "Refresh",
    refreshing: "Syncing…",
    loading: "Loading approval records…",
    emptyTitle: "No matching requests",
    emptyBody:
      "Try another view or search term. Create requests on desktop; use mobile to view and review them.",
    emptyTodo: "You’re all caught up",
    emptyTodoBody:
      "Follow requests you have voted on in My decisions. Your vote may not be the final request outcome.",
    count: "requests",
    pending: "In review",
    approved: "Approved",
    rejected: "Rejected",
    applicant: "Applicant",
    days: "days",
    duration: "Leave duration",
    submitted: "Submitted",
    updated: "Last updated",
    requestType: "Leave request",
    back: "Back to list",
    details: "Request details",
    reason: "Reason for leave",
    record: "Decision history",
    process: "Process overview",
    readonly: "Read only · Definition at submission",
    version: "Version",
    current: "Current step",
    approve: "Approve",
    reject: "Reject",
    reviewApprove: "Confirm approval",
    reviewReject: "Confirm rejection",
    opinion: "Decision note (optional)",
    opinionHint:
      "Your note is saved with this decision. You cannot edit it here after submitting.",
    placeholder: "Explain your decision…",
    cancel: "Cancel",
    confirm: "Submit decision",
    submitting: "Submitting…",
    singleConsequence:
      "Approval advances to the next step, or completes the request if this is the last step. Rejection ends the request.",
    allConsequence:
      "All must approve: every member must approve to advance. Any rejection ends the request.",
    anyConsequence:
      "Any may approve: one approval advances the request. Rejection ends it only after all members reject.",
    saved: "Your decision has been saved",
    savedPending:
      "The request is still in review. Follow its progress in My decisions.",
    savedTerminal:
      "The request has ended. Its latest status and decision history are below.",
    noAction: "No decision to make right now",
    noActionBody:
      "You may have already reviewed this step, it may not be your turn, or the request may have ended.",
    missingTitle: "Request unavailable",
    missingBody: "This request does not exist or this account cannot view it.",
    submitEvent: "Submitted request",
    approveEvent: "Approved",
    rejectEvent: "Rejected",
    noComment: "No decision note",
    allMode: "ALL · Everyone approves",
    anyMode: "ANY · One approval",
    singleMode: "One approver",
    completed: "Completed",
    upcoming: "Upcoming",
    skipped: "Not reached",
    votePending: "Awaiting vote",
    notNeeded: "No further vote needed",
    platformTitle: "Enterprise integrations are not connected",
    platformBody:
      "Feishu, WeCom and DingTalk sign-in and messaging are not connected. Demo accounts cannot sign in through this entry. Use the local browser demo entry instead.",
    platformFoot:
      "Feishu, WeCom and DingTalk sign-in and messaging are not connected",
    localOnly: "Local H5 demo",
    clearSearch: "Clear search",
    retry: "Retry",
    errors: {
      credentials:
        "Incorrect account or password. Check your local backend configuration.",
      expired:
        "Authentication expired. Sign in again; approval records remain on the server.",
      forbidden:
        "Your permissions changed. A refresh was attempted; review the latest state.",
      missing: "This account cannot access that request.",
      conflict:
        "This request has a newer decision. Review its latest history before continuing.",
      unavailable:
        "Service unavailable. No change is confirmed. Refresh and verify before retrying.",
      network:
        "Connection interrupted; no change is confirmed. A refresh was attempted. Verify history after reconnecting before retrying.",
      commentLong: "Decision notes must be at most 2,000 characters.",
    },
  },
};
export type Locale = keyof typeof copy;
