export const copy = {
  zh: {
    brand: "弧流",
    product: "移动审批",
    demo: "本地演示 · 真实后端",
    demoNote:
      "使用服务端配置的 Alice、Bob 或 Carol 演示账号。请勿输入真实人事或健康信息。",
    welcome: "让每一次审批，清晰有据。",
    loginHint: "登录后查看与你相关的申请。审批意见与处理记录由服务端保存。",
    username: "演示账号",
    password: "本地配置的密码",
    signIn: "进入工作台",
    signing: "正在验证…",
    signOut: "退出",
    identity: "当前身份",
    language: "English",
    loadFailed: "尚未获取完整待办",
    loadFailedBody: "连接失败时无法确认是否有待办。请恢复连接后重试。",
    inbox: "审批工作台",
    eyebrow: "ARCFLOW / WORKSPACE",
    subtitle: "专注于需要你判断的下一步。",
    todo: "待我审批",
    done: "我已处理",
    all: "与我相关",
    search: "搜索标题、原因或申请人",
    refresh: "刷新",
    refreshing: "正在同步…",
    loading: "正在获取审批记录…",
    emptyTitle: "这里暂时没有申请",
    emptyBody: "试试其他范围或关键词。申请由桌面端发起，移动端专注查看与审批。",
    emptyTodo: "当前没有待你审批的申请",
    emptyTodoBody:
      "已投票的会签申请可在「我已处理」继续追踪，最终结果以申请状态为准。",
    count: "项",
    pending: "审批中",
    approved: "已通过",
    rejected: "已驳回",
    applicant: "申请人",
    days: "天",
    duration: "请假时长",
    submitted: "发起时间",
    updated: "最后更新",
    requestType: "请假申请",
    back: "返回列表",
    details: "申请详情",
    reason: "申请事由",
    record: "审批记录",
    process: "流程概览",
    readonly: "只读 · 发起时的流程版本",
    version: "版本",
    current: "当前节点",
    approve: "同意",
    reject: "驳回",
    reviewApprove: "确认同意",
    reviewReject: "确认驳回",
    opinion: "审批意见（选填）",
    opinionHint: "意见将与本次决策一起保存到不可改写的审批记录。",
    placeholder: "写下你的判断依据…",
    cancel: "取消",
    confirm: "确认提交",
    submitting: "正在提交…",
    singleConsequence:
      "同意将进入下一节点；若这是最后一步，申请将通过。驳回将结束本次申请。",
    allConsequence:
      "会签：所有成员同意后进入下一节点；任一成员驳回即结束申请。",
    anyConsequence:
      "或签：任一成员同意即进入下一节点；只有所有成员驳回才结束申请。",
    saved: "你的决策已由服务端确认",
    savedPending: "申请仍在审批中，可在「我已处理」追踪后续。",
    savedTerminal: "申请已结束，以下为最新状态和审计记录。",
    noAction: "当前没有可执行操作",
    noActionBody: "你可能已投票、尚未轮到此节点，或申请已经结束。",
    missingTitle: "无法查看这条申请",
    missingBody: "申请不存在，或当前账号没有查看权限。",
    submitEvent: "发起申请",
    approveEvent: "同意",
    rejectEvent: "驳回",
    noComment: "未填写意见",
    allMode: "会签 · 全员同意",
    anyMode: "或签 · 任一同意",
    singleMode: "单人审批",
    completed: "已完成",
    upcoming: "待流转",
    skipped: "未执行",
    votePending: "待投票",
    notNeeded: "无需再投票",
    platformTitle: "企业平台尚未配置",
    platformBody:
      "飞书、企业微信和钉钉身份、消息能力均未接通。此入口不会回退为演示身份。请从本地浏览器演示入口登录。",
    platformFoot: "飞书 / 企业微信 / 钉钉：预留适配边界，尚未接通",
    localOnly: "H5 本地演示",
    clearSearch: "清空搜索",
    retry: "重试",
    errors: {
      credentials: "账号或密码不正确，请检查本地后端配置。",
      expired: "身份验证已失效，请重新登录。审批记录保存在后端。",
      forbidden: "权限已变化。已尝试刷新状态，请核对后再操作。",
      missing: "当前账号无法访问这条申请。",
      conflict: "这条申请已有新的处理结果。请查看最新记录后再决定。",
      unavailable: "服务暂时不可用。尚未确认变更，请刷新核对后重试。",
      network:
        "连接中断，尚未确认变更。已尝试刷新；恢复连接后请核对记录再重试。",
      commentLong: "审批意见最多 2000 个字符。",
    },
  },
  en: {
    brand: "ArcFlow",
    product: "Mobile approvals",
    demo: "Local demo · Live backend",
    demoNote:
      "Use the Alice, Bob or Carol demo account configured on your server. Do not enter real personnel or health information.",
    welcome: "Every decision, clear and accountable.",
    loginHint:
      "Sign in to see requests relevant to you. Decision notes and history are saved by the server.",
    username: "Demo account",
    password: "Locally configured password",
    signIn: "Open workspace",
    signing: "Verifying…",
    signOut: "Sign out",
    identity: "Signed in as",
    language: "中文",
    loadFailed: "Worklist not confirmed",
    loadFailedBody:
      "A failed connection cannot confirm whether you have tasks. Reconnect and retry.",
    inbox: "Approval workspace",
    eyebrow: "ARCFLOW / WORKSPACE",
    subtitle: "Focus on the next decision that needs you.",
    todo: "To review",
    done: "My decisions",
    all: "Related to me",
    search: "Search title, reason or applicant",
    refresh: "Refresh",
    refreshing: "Syncing…",
    loading: "Loading approval records…",
    emptyTitle: "No matching requests",
    emptyBody:
      "Try another view or search. Requests are created on desktop; mobile focuses on review and decisions.",
    emptyTodo: "You’re all caught up",
    emptyTodoBody:
      "Follow requests you have voted on in My decisions. Your vote may not be the final request outcome.",
    count: "requests",
    pending: "In review",
    approved: "Approved",
    rejected: "Rejected",
    applicant: "Applicant",
    days: "days",
    duration: "Leave duration",
    submitted: "Submitted",
    updated: "Last updated",
    requestType: "Leave request",
    back: "Back to list",
    details: "Request details",
    reason: "Reason for leave",
    record: "Decision history",
    process: "Process overview",
    readonly: "Read only · Definition at submission",
    version: "Version",
    current: "Current step",
    approve: "Approve",
    reject: "Reject",
    reviewApprove: "Confirm approval",
    reviewReject: "Confirm rejection",
    opinion: "Decision note (optional)",
    opinionHint:
      "Your note is saved with this decision in the immutable history.",
    placeholder: "Explain your decision…",
    cancel: "Cancel",
    confirm: "Submit decision",
    submitting: "Submitting…",
    singleConsequence:
      "Approval advances to the next step, or completes the request if this is the last step. Rejection ends the request.",
    allConsequence:
      "All must approve: every member must approve to advance. Any rejection ends the request.",
    anyConsequence:
      "Any may approve: one approval advances the request. Rejection ends it only after all members reject.",
    saved: "Your decision is confirmed by the server",
    savedPending:
      "The request is still in review. Follow its progress in My decisions.",
    savedTerminal:
      "The request has ended. Its latest status and audit history are below.",
    noAction: "No action available right now",
    noActionBody:
      "You may have voted, this step may not be current, or the request may have ended.",
    missingTitle: "Request unavailable",
    missingBody: "This request does not exist or this account cannot view it.",
    submitEvent: "Submitted request",
    approveEvent: "Approved",
    rejectEvent: "Rejected",
    noComment: "No decision note",
    allMode: "ALL · Everyone approves",
    anyMode: "ANY · One approval",
    singleMode: "One approver",
    completed: "Completed",
    upcoming: "Upcoming",
    skipped: "Not reached",
    votePending: "Awaiting vote",
    notNeeded: "No further vote needed",
    platformTitle: "Enterprise host is not configured",
    platformBody:
      "Feishu, WeCom and DingTalk identity and messaging are not connected. This entry will not fall back to a demo identity. Use the local browser demo entry to sign in.",
    platformFoot:
      "Feishu / WeCom / DingTalk: adapter boundaries only; not connected",
    localOnly: "Local H5 demo",
    clearSearch: "Clear search",
    retry: "Retry",
    errors: {
      credentials:
        "Incorrect account or password. Check your local backend configuration.",
      expired:
        "Authentication expired. Sign in again; approval records remain on the server.",
      forbidden:
        "Your permissions changed. A refresh was attempted; review the latest state.",
      missing: "This account cannot access that request.",
      conflict:
        "This request has a newer decision. Review its latest history before continuing.",
      unavailable:
        "Service unavailable. No change is confirmed. Refresh and verify before retrying.",
      network:
        "Connection interrupted; no change is confirmed. A refresh was attempted. Verify history after reconnecting before retrying.",
      commentLong: "Decision notes must be at most 2,000 characters.",
    },
  },
};
export type Locale = keyof typeof copy;
