import { test, expect } from '@playwright/test'
async function designer(page) { await page.getByTestId('process-tab').click(); await page.getByTestId('workspace-language').selectOption('en'); await page.getByTestId('select-step').first().click() }
async function stage(page, index) { await page.getByTestId('select-step').nth(index - 1).click() }
async function login(page, user) {
  await page.getByLabel('Demo account').selectOption(user)
  await page.getByLabel('Password', { exact: true }).fill(process.env[`APPROVAL_${user.toUpperCase()}_PASSWORD`])
  await page.getByRole('button', { name: 'Enter workspace' }).click()
  await expect(page.getByRole('heading', { name: 'Business approvals', exact: true })).toBeVisible()
}
async function switchUser(page, user) { await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await login(page, user) }
async function select(page, title) { await page.getByRole('button').filter({ has: page.getByText(title, { exact: true }) }).click() }
async function requests(page) { await page.getByRole('navigation').getByRole('button', { name: /Requests/ }).click() }
async function submit(page, title) {
  await requests(page)
  await page.getByLabel('Title', { exact: true }).fill(title)
  await page.getByLabel('Reason', { exact: true }).fill('Synthetic group browser QA. No personal information.')
  await page.getByRole('button', { name: 'Submit request', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Request submitted')
}
async function capture(page, testInfo, name) {
  await expect(page.getByLabel('Password', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath(`${name}.png`), fullPage: true })
}

test('ALL/ANY edit, publish, participant votes, repeated clicks, reload, immutable snapshots and recovery', async ({ page }, testInfo) => {
  test.setTimeout(120_000)
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/'); await login(page, 'alice'); await designer(page)
  await page.getByTestId('process-name').fill('Parallel synthetic review')
  await page.getByLabel('Step 1 name', { exact: true }).fill('Team group')
  // The preceding sequential journey can leave Carol first; pin the intended member order.
  await page.getByLabel('Step 1 approver', { exact: true }).selectOption('bob')
  await page.getByLabel('Step 1 review mode', { exact: true }).selectOption('ALL')
  const groupId = await page.locator('.flow-node.parallelApproval').getAttribute('data-step-id')
  await page.getByLabel('Step 1 participant Carol', { exact: true }).uncheck()
  await expect(page.getByTestId('publish')).toBeDisabled()
  await page.getByLabel('Step 1 participant Carol', { exact: true }).check()
  if (await page.getByTestId('select-step').count() < 2) await page.getByTestId('add-step').click()
  await stage(page, 2)
  await page.getByLabel('Step 2 name', { exact: true }).fill('Final review')
  await page.getByLabel('Step 2 approver', { exact: true }).selectOption('carol')
  await page.getByTestId('publish').dblclick()
  await expect(page.getByRole('status')).toContainText('published')
  await expect(page.getByTestId('publish')).toBeDisabled()
  await stage(page, 1)
  await capture(page, testInfo, '01-all-designer')
  await submit(page, 'ALL participant workflow')
  await switchUser(page, 'carol'); await select(page, 'ALL participant workflow')
  await expect(page.getByRole('button', { name: 'Approve vote', exact: true })).toBeVisible()
  await page.getByLabel('Decision comment').fill('Carol approves the group')
  let votes = 0
  await page.route('**/api/requests/*/decisions', async route => { votes++; await new Promise(resolve => setTimeout(resolve, 250)); await route.continue() })
  await page.getByRole('button', { name: 'Approve vote', exact: true }).dblclick()
  await expect(page.getByRole('status')).toHaveText('Vote recorded. This group is still pending; awaiting Bob.')
  expect(votes).toBe(1); await page.unroute('**/api/requests/*/decisions')
  await expect(page.locator('.participant-votes')).toContainText('Carol · Approved')
  await expect(page.locator('.participant-votes')).toContainText('Bob · Awaiting vote')
  await expect(page.getByRole('button', { name: /^Approve/ })).toHaveCount(0)
  await capture(page, testInfo, '02-all-partial-votes')
  await switchUser(page, 'bob'); await select(page, 'ALL participant workflow')
  await page.getByRole('button', { name: 'Approve vote', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('still pending; Carol reviews the next step')
  await expect(page.locator(`.snapshot-steps [data-step-id="${groupId}"]`)).toHaveClass(/approved/)
  await switchUser(page, 'carol'); await select(page, 'ALL participant workflow')
  await page.getByRole('button', { name: 'Approve request', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Request approved.')
  await page.reload(); await expect(page.getByLabel('Password', { exact: true })).toHaveValue('')
  await login(page, 'alice'); await select(page, 'ALL participant workflow')
  await expect(page.locator('.detail > .card-heading .status')).toHaveText('approved')
  await expect(page.locator('.participant-votes')).toContainText('Carol approves the group')

  await designer(page)
  await page.getByLabel('Step 1 review mode', { exact: true }).selectOption('ANY')
  // A failed refresh preserves the group draft and permits recovery.
  await page.route('**/api/requests', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"message":"Synthetic temporary outage"}' }))
  await page.getByTestId('refresh').click(); await expect(page.getByRole('alert')).toContainText('Synthetic temporary outage')
  await expect(page.getByLabel('Step 1 review mode', { exact: true })).toHaveValue('ANY')
  await page.unroute('**/api/requests'); await page.getByTestId('refresh').click()
  await expect(page.getByRole('status')).toContainText('local draft is preserved')
  await page.getByTestId('publish').click(); await expect(page.getByRole('status')).toContainText('published')
  await requests(page)
  await expect(page.getByTestId('instance-snapshot')).toContainText('ALL · Bob + Carol')
  await expect(page.getByTestId('submission-template')).toContainText('ANY · Bob + Carol')
  await submit(page, 'ANY rejected vote then approval')
  await switchUser(page, 'bob'); await select(page, 'ANY rejected vote then approval')
  await page.getByRole('button', { name: 'Reject vote', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Vote recorded. This group is still pending; awaiting Carol.')
  await switchUser(page, 'carol'); await select(page, 'ANY rejected vote then approval')
  await page.getByRole('button', { name: 'Approve vote', exact: true }).click()
  await expect(page.locator('.participant-votes')).toContainText('Bob · Rejected')
  await expect(page.locator('.participant-votes')).toContainText('Carol · Approved')
  await page.getByRole('button', { name: 'Approve request', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Request approved.')

  await switchUser(page, 'alice'); await submit(page, 'ANY early approval')
  await switchUser(page, 'bob'); await select(page, 'ANY early approval')
  await page.getByRole('button', { name: 'Approve vote', exact: true }).click()
  await expect(page.locator('.participant-votes')).toContainText('Carol · Not required')
  await capture(page, testInfo, '03-any-unneeded-vote')
  await switchUser(page, 'carol'); await select(page, 'ANY early approval')
  await page.getByRole('button', { name: 'Approve request', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Request approved.')
  await page.setViewportSize({ width: 390, height: 844 })
  await capture(page, testInfo, '04-mobile-group-result')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
