import { test, expect } from '@playwright/test'
// Run after existing journeys or alone. Uses the existing disposable suite server.
test('Chinese-first workbench insertion, validation focus, history, responsive inspector and publication', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('Demo account').selectOption('alice')
  await page.getByLabel('Password', { exact:true }).fill(process.env.APPROVAL_ALICE_PASSWORD)
  await page.getByRole('button', { name:'Enter workspace' }).click()
  await page.getByTestId('process-tab').click()
  await page.getByTestId('workspace-language').selectOption('zh')
  await expect(page.getByTestId('workspace-language')).toHaveValue('zh')
  const count = await page.getByTestId('select-step').count()
  await page.getByRole('button', { name:'在节点 1 前插入审批节点', exact:true }).click()
  await expect(page.getByTestId('select-step')).toHaveCount(count + 1)
  const id = await page.locator('[data-testid="select-step"][aria-pressed=true]').getAttribute('data-step-id')
  await expect(page.getByLabel('节点 1 名称', {exact:true})).toBeFocused()
  await page.getByLabel('节点 1 名称', {exact:true}).fill('跨团队协同审批')
  await page.getByLabel('节点 1 审批方式', {exact:true}).selectOption('ANY')
  await expect(page.locator('.rule-callout')).toContainText('任一同意即通过，全部拒绝才驳回')
  await page.getByLabel('节点 1 参与人 Carol', {exact:true}).uncheck()
  await expect(page.getByTestId('publish')).toBeDisabled()
  await page.locator('.validation-list button').click()
  await expect(page.locator('.participant-picker input').first()).toBeFocused()
  await page.screenshot({path:testInfo.outputPath('01-workbench-invalid-group.png'),fullPage:true})
  await page.getByTestId('undo').click()
  await expect(page.getByLabel('节点 1 参与人 Carol', {exact:true})).toBeChecked()
  await expect(page.getByTestId('publish')).toBeEnabled()
  await page.screenshot({path:testInfo.outputPath('02-workbench-any-inspector.png'),fullPage:true})
  await page.getByLabel('节点 1 名称', {exact:true}).press('Escape')
  await expect(page.locator(`[data-select-id="${id}"]`)).toBeFocused()
  await page.setViewportSize({width:390,height:844})
  await page.locator('.mobile-designer-switch').getByRole('button').first().click()
  await page.getByTestId('select-step').last().click()
  await expect(page.locator('.step-inspector')).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({path:testInfo.outputPath('03-workbench-narrow-inspector.png'),fullPage:true})
  await page.setViewportSize({width:1440,height:1000})
  await page.getByTestId('workspace-language').selectOption('en')
  await page.getByTestId('publish').click()
  await expect(page.getByRole('status')).toContainText('published')
  await expect(page.getByTestId('undo')).toBeDisabled()
})
